### ISSUE TITLE
Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT

### ISSUE THREAD

**Issue by ivan** [juxt/jig#11]
Not sure if `master` (ab71db8e884ff50c4e9fa313727ec8ea92b7673c) is supposed to work at this time, but I couldn't try it out:

```
jig# lein repl
Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Exception in thread "Thread-4" clojure.lang.ExceptionInfo: Could not resolve dependencies {:exit-code 1, :suppress-msg true}
        at clojure.core$ex_info.invoke(core.clj:4327)
        at leiningen.core.classpath$fn__2759.invoke(classpath.clj:180)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.core$memoize$fn__5049.doInvoke(core.clj:5735)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:299)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:621)
        at leiningen.core.classpath$resolve_dependencies.doInvoke(classpath.clj:343)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at leiningen.core.eval$prep.invoke(eval.clj:56)
        at leiningen.core.eval$eval_in_project.invoke(eval.clj:323)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:619)
        at leiningen.repl$server$fn__7443.invoke(repl.clj:201)
        at clojure.lang.AFn.applyToHelper(AFn.java:159)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:621)
        at clojure.core$bound_fn_STAR_$fn__4102.doInvoke(core.clj:1810)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT in clojars (https://clojars.org/repo/)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:585)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:617)
        at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:594)
        at clojure.lang.RestFn.invoke(RestFn.java:2088)
        at leiningen.core.classpath$fn__2759.invoke(classpath.clj:170)
        ... 30 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT in clojars (https://clojars.org/repo/)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        ... 42 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT in clojars (https://clojars.org/repo/)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:947)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
```

```
jig# lein install
Could not find artifact jig:protocols:jar:2.0.0-RC6-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by malcolmsparks** [comment]
Yes, others have reported this. I need to release RC7 because it separates
the Jig Lifecycle protocol from the Jig workflow (I wanted to have this
separation).

For now, try

lein install-all

Please forgive these issues while I get them straightened out during the RC
cycle.

Regards,

Malcolm
