### ISSUE TITLE
"1.4.0-RC1" tag breaks jig

### ISSUE THREAD

**Issue by ivan** [juxt/jig#6]
```
test# ~/bin/lein version
Leiningen 2.3.4 on Java 1.7.0_25 OpenJDK 64-Bit Server VM

test# git clone https://github.com/juxt/jig
Cloning into 'jig'...
cd jigremote: Counting objects: 682, done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 682 (delta 296), reused 659 (delta 274)
Receiving objects: 100% (682/682), 418.15 KiB | 625.00 KiB/s, done.
Resolving deltas: 100% (296/296), done.
Checking connectivity... done

test# cd jig

test/jig# ~/bin/lein repl
java.lang.Exception: Error loading /home/at/test/jig/project.clj
        at leiningen.core.project$read$fn__3326.invoke(project.clj:696)
        at leiningen.core.project$read.invoke(project.clj:693)
        at leiningen.core.project$read.invoke(project.clj:703)
        at leiningen.core.main$_main$fn__3092.invoke(main.clj:294)
        at leiningen.core.main$_main.doInvoke(main.clj:290)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.lang.AFn.applyToHelper(AFn.java:161)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.main$main_opt.invoke(main.clj:335)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:423)
        at clojure.lang.AFn.applyToHelper(AFn.java:167)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: Invalid number: 0-RC1
        at clojure.lang.LispReader.readNumber(LispReader.java:258)
        at clojure.lang.LispReader.read(LispReader.java:176)
        at clojure.lang.RT.readString(RT.java:1738)
        at clojure.core$read_string.invoke(core.clj:3427)
        at leiningen.core.project$get_version.invoke(project-header.clj:54)
        at leiningen.core.project$eval497.invoke(project.clj:18)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.lang.RT$3.invoke(RT.java:318)
        at leiningen.core.project$read$fn__3326.invoke(project.clj:694)
        ... 16 more
```

**Comment by malcolmsparks** [comment]
Thanks - I've renamed to 1.4.0. But 1.4.0 should still be considered
somewhat experimental as noted in the README.md. That said, I've been using
it on my own projects for almost a week now and it seems to be OK.
